### PR TITLE
Dragonflight Update

### PR DESCRIPTION
**Pull request by Roskanne**
Hello!

I'm not sure my request is at the correct place, and I'm sorry for that.

I would like to know if any update aboutthe newest expansion of WoW retail is possible (Dragonflight).

I use this addon since WOTLK (retail one!)  and i'm really sad that it makes now LUA error on the screen while playing.
I could change it to another one that do quite the same, but this one is elegant on the screen, aestethic :)

I wish my message will find someone <3

Roskanne.

### CODE REVIEW

**Comment by Vilacard** [comment]
There is Rookdorf's pull request (https://github.com/nyyr/ArcHUD3/pull/64) as well as ARCadia (https://github.com/eiymba/arcadia). Arcadia is looking like it'll be a successor to ArcHUD, but it hasn't been updated in a month or so. I'm hoping work will continue on it, but it seems to spit out the same errors as Rookdorf's pull. At least for me, arcs for 'secondary' powers (such as mana for shadow, charges for arcane, I assume mana for bear+cats) don't show up at all. Otherwise they seem to work fine.

**Comment by rookdorf** [comment]
@Vilacard Comment what errors you get on my PR if you want, I didn't continue with support like empowered spell cast bars or anything but I'm at least trying to make it function and not currently getting any errors personally. I can check those out when I get a chance

**Comment by Vilacard** [comment]
@Rookdorf Is there an easy way to copy a ton of them at the same time? With just Addon List, Advanced Interface Options, and your ArcHUD3 PR I get 138 lua errors. Most of them seem to be repeats, so I'll just list a few:

Message: Interface/AddOns/ArcHUD3/Locales/enUS.lua:3: attempt to call global 'LibStub' (a nil value)
Time: Thu Dec 22 16:40:29 2022
Count: 1
Stack: Interface/AddOns/ArcHUD3/Locales/enUS.lua:3: attempt to call global 'LibStub' (a nil value)
[string "@Interface/AddOns/ArcHUD3/Locales/enUS.lua"]:3: in main chunk

Locals: (*temporary) = nil
(*temporary) = "AceLocale-3.0"
(*temporary) = "attempt to call global 'LibStub' (a nil value)"

There's also the same error for deDE.lua, ruRU.lua, and zhCN.lua but on a line or two earlier or later.


Message: Interface/AddOns/ArcHUD3/Core.lua:4: attempt to call global 'LibStub' (a nil value)
Time: Thu Dec 22 16:40:29 2022
Count: 1
Stack: Interface/AddOns/ArcHUD3/Core.lua:4: attempt to call global 'LibStub' (a nil value)
[string "@Interface/AddOns/ArcHUD3/Core.lua"]:4: in main chunk

Locals: (*temporary) = nil
(*temporary) = "AceAddon-3.0"
(*temporary) = "attempt to call global 'LibStub' (a nil value)"

Same error for Frames.lua, ModuleCore.lua, Config.lua, MirrorTimer,lua, Health.lua, Power.lua, Stagger.lua, CustomBuff.lua, 



Message: Interface/AddOns/ArcHUD3/Nameplates.lua:5: attempt to index global 'ArcHUD' (a nil value)
Time: Thu Dec 22 16:40:29 2022
Count: 1
Stack: Interface/AddOns/ArcHUD3/Nameplates.lua:5: attempt to index global 'ArcHUD' (a nil value)
[string "@Interface/AddOns/ArcHUD3/Nameplates.lua"]:5: in main chunk

Locals: (*temporary) = nil
(*temporary) = <function> defined @Interface/AddOns/ArcHUD3/Nameplates.lua:5
(*temporary) = "attempt to index global 'ArcHUD' (a nil value)"

Same error for BlizzardFrames.lua, Utils,lua, Anchors.lua, Casting.lua, TargetHealth.lua, TargetPower.lua, TargetCasting.lua, PetHealth.lua, PetPower.lua, FocusHealth.lua, FocusPower.lua, FocusCasting.lua, PowerTemplate.lua, ArcaneCharges.lua, ComboPoints.lua, ComboPointsDruid.lua, HolyPower.lua, SoulShards.lua, ManaShadowPriest.lua, ManaBalanceDruid.lua, ManaDruid.lua, ManaElementalShaman.lua, Chi.lua, Runes.lua, 



Message: Interface/AddOns/ArcHUD3/embeds.xml:3 Error loading Interface/AddOns/ArcHUD3/Libs/LibStub/LibStub.lua
Time: Thu Dec 22 16:40:30 2022
Count: 1

Same error for the other Libs


Message: Interface/AddOns/ArcHUD3/Locales/enUS.lua:1 (null)
Time: Thu Dec 22 16:40:30 2022
Count: 1

Same error for the other locales.


Message: Interface/AddOns/ArcHUD3/Core.lua:1 (null)
Time: Thu Dec 22 16:40:30 2022
Count: 1

Same error for Frames, Nameplates, BlizzardFrames, Utils, ModuleCore, Config, Anchors, MirrorTimer, Health, Power, Casting, TargetHealth, TargetPower, TargetCasting,  PetHealth, PetPower, FocusHealth, FocusPower, FocusCasting, PowerTemplate, ArcaneCharges, ComboPoints, ComboPointsDruid, HolyPower, SoulShards, ManaShadowPriest, ManaBalanceDruid, ManaDruid, ManaElementalShaman, Chi, Runes, Stagger, CustomBuff,


Message: Interface/AddOns/ArcHUD3/RingTemplate.xml:64 Unrecognized XML attribute: maxFramerate
Time: Thu Dec 22 16:40:30 2022
Count: 1

Same error but instead of maxFramerate it's  change on lines 81 and 101.


Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/ArcHUD3/embeds.xml:3 Error loading Interface/AddOns/ArcHUD3/Libs/LibStub/LibStub.lua
Time: Thu Dec 22 16:40:30 2022
Count: 1

Same error for the other libs.



Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/ArcHUD3/Locales/enUS.lua:1 (null)
Time: Thu Dec 22 16:40:30 2022
Count: 1

Same error for the other locales, Core, Frames, Nameplates, BlizzardFrames, Utils, ModuleCore, Config, Anchors, MirrorTimer, Health, Power, Casting, TargetHealth, TargetPower, TargetCasting,  PetHealth, PetPower, FocusHealth, FocusPower, FocusCasting, PowerTemplate, ArcaneCharges, ComboPoints, ComboPointsDruid, HolyPower, SoulShards, ManaShadowPriest, ManaBalanceDruid, ManaDruid, ManaElementalShaman.

**Comment by rookdorf** [comment]
I think a good amount of those stem from not making a fresh build of the addon which updates the libraries, but I'm not totally sure (and don't have an easy way to provide instructions on building it yourself, but feel free to look into it). I can take a closer look after the holidays though

**Comment by Vilacard** [comment]
My apologies, this all seems to be an error on my part. When I redownloaded your release, I never put the libs in. I just downloaded the latest Ace3 release from Curseforge and the correct ones in the lib folder. Now i only get 6 errors:

Message: Interface/AddOns/ArcHUD3/RingTemplate.xml:64 Unrecognized XML attribute: maxFramerate
Time: Fri Dec 23 08:40:20 2022
Count: 1


Message: Interface/AddOns/ArcHUD3/RingTemplate.xml:81 Unrecognized XML attribute: change
Time: Fri Dec 23 08:40:20 2022
Count: 1


Message: Interface/AddOns/ArcHUD3/RingTemplate.xml:101 Unrecognized XML attribute: change
Time: Fri Dec 23 08:40:20 2022
Count: 1


Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/ArcHUD3/RingTemplate.xml:64 Unrecognized XML attribute: maxFramerate
Time: Fri Dec 23 08:40:20 2022
Count: 1


Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/ArcHUD3/RingTemplate.xml:81 Unrecognized XML attribute: change
Time: Fri Dec 23 08:40:20 2022
Count: 1


Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/ArcHUD3/RingTemplate.xml:101 Unrecognized XML attribute: change
Time: Fri Dec 23 08:40:20 2022
Count: 1



None of which seem to affect actual gameplay/functionality from playing for 5 minutes. The secondary power rings (shadow priest mana, mage arcane charges, I'm sure the others I listed before) work fine now.

Thanks!

**Comment by Roskanne** [comment]
Here is one (at least) error that I have :

Message: Interface/AddOns/ArcHUD3/RingTemplate.xml:64 Unrecognized XML attribute: maxFramerate
Time: Sat Dec 24 04:42:14 2022
Count: 1
Stack: Interface/AddOns/ArcHUD3/RingTemplate.xml:64 Unrecognized XML attribute: maxFramerate

Locals: <none>

**Comment by rookdorf** [comment]
Both of those should be fixed in my PR already, you can see I removed those defunct attributes here: https://github.com/nyyr/ArcHUD3/pull/64/files#diff-2b5c73922d7bf8abf4d9a3bb25d524db68b25aeb88efb4f3701db5f7d7d15630 
Tried to recreate the errors on my end, but I already have those changes I made, so I'm not getting any currently

**Comment by nyyr** [comment]
Nice to see that somebody picked up development :) You probably guessed that I'm no longer active.

@rookdorf Any suggestions what/how to merge? I could probably also add you as collaborator if you are willing to.

**Comment by nyyr** [comment]
I added you as Collaborator, can you check whether you can do the merging?

For publishing the packages, I used Travis CI previously, but I guess, this should be migrated to Github Actions now. Do you have experience with GH Actions? If not, we can have a look into that together.

The packager I used is actually now offering direct integration with GH Actions: https://github.com/BigWigsMods/packager 

So this should be straight forward.

**Comment by rookdorf** [comment]
Yup, just merged! I don't have a lot of experience with GH actions, though I did use the BigWigs packager to make myself a local copy without doing the publish step. I think I ran into where I'd need the Curse key to push. Didn't try to automate anything yet though

**Comment by nyyr** [comment]
Let's follow-up here: #70. Please close this PR if it is obsolete.

**Pull request closed without merging**
