### PR TITLE
makes changes based on bfa 8.0.1 changelog

### PR DESCRIPTION
**Pull request by jnrepo**
closes https://github.com/nyyr/ArcHUD3/issues/27

- address new changes made in bfa 8.0.1 patch
- https://wow.gamepedia.com/Patch_8.0.1/API_changes

### CODE REVIEW

**Comment by jnrepo** [comment]
this right now will fix the `UNIT_POWER` errors and will get the UI to show up again

**Comment by jnrepo** [comment]
Will now fix the error with the event "PET_BAR_CHANGED". Seems that its not called "PET_BAR_UPDATE_USABLE".

**Comment by Chickenchasr** [comment]
There is another event worth checking out for the petbar : PET_BAR_UPDATE.

**Comment by jnrepo** [comment]
@nyyr cool sounds good. I could not find any official blizzard documentation for addon events, so I kind of looked here http://wowprogramming.com/docs/events.html and used one that seemed similar to the event that was throwing an error

**Comment by nyyr** [comment]
I think this event only fires if the pet bar is changing from a disabled state (e.g., when mounted) to an enabled state (when dismounted). Thus, it is not necessary here. Feel free to raise an issue if you encounter problems with the pet arc updates.

**Pull request closed without merging**
